title: Azure AD Audit Logs mapping for Azure Log Analytics
order: 20
backends:
  - ala
  - ala-rule
fieldmappings:
  category: Category
  activityDisplayName: OperationName
  loggedByService: LoggedByService
  result: Result
  resultReason: ResultReason # Indicates the reason for failure if the result is failure or timeout.
  status.errorCode: ErrorCode
  status.failureReason: FailureReason
  initiatedBy.user.userPrincipalName: initiatedBy.user.userPrincipalName
