title: Elastic Exported Fields Mapping For OneLogin logs
order: 20
backends:
  - es-qs
  - es-dsl
  - es-rule
  - kibana
  - kibana-ndjson
  - xpack-watcher
  - elastalert
  - elastalert-dsl
fieldmappings:
